# Generated by Django 4.2.9 on 2026-01-29 00:13

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('detected_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('asset', models.CharField(db_index=True, max_length=20)),
                ('buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('sell_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_qty_available', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('sell_qty_available', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('spread_pct', models.DecimalField(decimal_places=6, max_digits=10)),
                ('spread_absolute', models.DecimalField(decimal_places=8, max_digits=20)),
                ('simulated', models.BooleanField(default=False)),
                ('simulated_at', models.DateTimeField(blank=True, null=True)),
                ('trade_amount', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('gross_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('total_fees', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('slippage_cost', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('latency_cost', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('net_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('profitable', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('websocket_url', models.URLField(blank=True)),
                ('maker_fee', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=8)),
                ('taker_fee', models.DecimalField(decimal_places=6, default=Decimal('0.001'), max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_volatility', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('buy_book_depth', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('sell_book_depth', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('detection_latency_ms', models.IntegerField(null=True)),
                ('hour_of_day', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sim_log', to='api.arbitrageevent')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connected', models.BooleanField(default=False)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='api.exchange')),
            ],
        ),
        migrations.AddField(
            model_name='arbitrageevent',
            name='buy_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_opportunities', to='api.exchange'),
        ),
        migrations.AddField(
            model_name='arbitrageevent',
            name='sell_exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sell_opportunities', to='api.exchange'),
        ),
        migrations.CreateModel(
            name='PriceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset', models.CharField(db_index=True, max_length=20)),
                ('bid', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ask', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bid_qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('ask_qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='api.exchange')),
            ],
            options={
                'get_latest_by': 'timestamp',
                'indexes': [models.Index(fields=['asset', 'exchange', '-timestamp'], name='api_pricesn_asset_a5f5a2_idx'), models.Index(fields=['-timestamp'], name='api_pricesn_timesta_5fa8e1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='arbitrageevent',
            index=models.Index(fields=['asset', '-detected_at'], name='api_arbitra_asset_f9174d_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrageevent',
            index=models.Index(fields=['-spread_pct'], name='api_arbitra_spread__f22529_idx'),
        ),
        migrations.AddIndex(
            model_name='arbitrageevent',
            index=models.Index(fields=['simulated', '-detected_at'], name='api_arbitra_simulat_e4141c_idx'),
        ),
    ]
